# spark_hadoop_base will install Spark and Hadoop
FROM nicolasmartinbekier/spark_hadoop_base:v0.1 

# Copy configuration files
COPY core-site.xml HADOOP_HOME/etc/hadoop/
COPY hdfs-site.xml HADOOP_HOME/etc/hadoop/
RUN groupadd -r ubuntu && useradd -m -r -g ubuntu ubuntu 
COPY worker-configuration.sh /home/ubuntu/
RUN chown ubuntu /home/ubuntu/worker-configuration.sh && chmod +x /home/ubuntu/worker-configuration.sh
USER ubuntu

# Run starting configuration
CMD ["/bin/bash", "/home/ubuntu/worker-configuration.sh"] 


