FROM ubuntu:20.04
# Initial installations
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install ssh
RUN apt-get install pdsh
RUN apt install -y openjdk-8-jre-headless
RUN apt install -y scala
RUN apt install -y wget

# Hadoop installation
ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
RUN wget http://apache.mirrors.tds.net/hadoop/common/hadoop-3.3.0/hadoop-3.3.0.tar.gz
RUN tar -xvf hadoop-3.3.0.tar.gz
RUN mv hadoop-3.3.0/ /usr/local/hadoop
ENV HADOOP_HOME="/usr/local/hadoop"
ENV PATH="${PATH}:$HADOOP_HOME/bin"
ENV PATH="${PATH}:$HADOOP_HOME/sbin"
ENV HADOOP_MAPRED_HOME="${HADOOP_HOME}"
ENV HADOOP_COMMON_HOME="${HADOOP_HOME}"
ENV HADOOP_HDFS_HOME="${HADOOP_HOME}"
ENV YARN_HOME="${HADOOP_HOME}"

# Spark installation
RUN wget https://archive.apache.org/dist/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz
RUN tar xvf spark-3.2.0-bin-hadoop3.2.tgz
RUN mv spark-3.2.0-bin-hadoop3.2/ /usr/local/spark
ENV PATH="${PATH}:$SPARK_HOME/bin"
ENV SPARK_HOME="/usr/local/spark"
ENV SPARK_NO_DAEMONIZE="true"

RUN rm hadoop-3.3.0.tar.gz spark-3.2.0-bin-hadoop3.2.tgz
RUN sleep 15
